/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Awards } from "./Awards";
import { AwardsCountArgs } from "./AwardsCountArgs";
import { AwardsFindManyArgs } from "./AwardsFindManyArgs";
import { AwardsFindUniqueArgs } from "./AwardsFindUniqueArgs";
import { DeleteAwardsArgs } from "./DeleteAwardsArgs";
import { AwardsService } from "../awards.service";
@graphql.Resolver(() => Awards)
export class AwardsResolverBase {
  constructor(protected readonly service: AwardsService) {}

  async _awardsItemsMeta(
    @graphql.Args() args: AwardsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Awards])
  async awardsItems(
    @graphql.Args() args: AwardsFindManyArgs
  ): Promise<Awards[]> {
    return this.service.awardsItems(args);
  }

  @graphql.Query(() => Awards, { nullable: true })
  async awards(
    @graphql.Args() args: AwardsFindUniqueArgs
  ): Promise<Awards | null> {
    const result = await this.service.awards(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Awards)
  async deleteAwards(
    @graphql.Args() args: DeleteAwardsArgs
  ): Promise<Awards | null> {
    try {
      return await this.service.deleteAwards(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
